language: node_js
os:
  - linux
  - osx
  # - windows
node_js:
  - "10"
  - "node"
install:
  - yarn
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
default-script: &default-script
  script: "yarn test:${TRAVIS_JOB_NAME}"
  node_js: "10"
matrix:
  include:
    - name: "crtsh"
      <<: *default-script
    - name: "cryptcheck"
      <<: *default-script
    - name: "hstspreload"
      <<: *default-script
    - name: "httpobservatory"
      <<: *default-script
    - name: "lighthouse"
      <<: *default-script
    - name: "psi"
      <<: *default-script
    - name: "securityheaders"
      <<: *default-script
    - name: "ssldecoder"
      <<: *default-script
    - name: "ssldecoder-fast"
      <<: *default-script
    - name: "ssllabs"
      <<: *default-script
    - name: "webbkoll"
      <<: *default-script
    - name: "webhint"
      <<: *default-script
    - name: "pkg-build"
      node_js: "10"
      script:
        - yarn global add pkg
        - "pkg index.js -o website-checks --targets linux,macos,win"
        - "ls -al"